title: Yujuan Gao
email: yujuan.gao@ufl.edu
description: >-
  Personal website of Yujuan Gao. Development Economics, Impact Evaluation, and Causal Inference.
baseurl: "" 
url: "https://yujuangao.github.io"

theme: minima

github_username: yujuangao
